// OpenScad script
// https://www.openscad.org/

// Generated by "trilateration_transform.cpp"
// https://github.com/kwikius/Trilateration

module show_sphere(pos,radius)
{
   translate(pos){
      sphere(r = radius, $fn = 50);
   }
}

color("blue"){
   show_sphere([4, 5, 6], 7.5);
   show_sphere([10, 11, 5.6], 7);
   show_sphere([13, 4.5, 5.5], 5);
}

color("yellow"){
   show_sphere([10.4923, 5.37433, 9.73637], 1);
}

